services:
  code-server:
    build:
      context: .
    image: code-server
    ports:
      - "8181:8080"
    container_name: code-server
    restart: unless-stopped
    volumes:
      - ./settings.json:/home/coder/.local/share/code-server/User/settings.json
      - ./keybindings.json:/home/coder/.local/share/code-server/User/keybindings.json
